// Restaurants
export const restaurants = [
  {
    id: "1",
    name: "Burger Palace",
    image: "/placeholder.svg?height=300&width=500",
    cuisine: "Burgers",
    rating: 4.7,
    deliveryTime: "25-35",
    minimumOrder: 15,
    address: "123 Burger St, Food City, FC 12345",
    status: "active",
    owner: {
      id: "user3",
      name: "John Restaurant",
      email: "john@restaurant.com",
    },
  },
  {
    id: "2",
    name: "Pizza Heaven",
    image: "/placeholder.svg?height=300&width=500",
    cuisine: "Pizza",
    rating: 4.5,
    deliveryTime: "30-45",
    minimumOrder: 20,
    address: "456 Pizza Ave, Food City, FC 12345",
    status: "active",
    owner: {
      id: "user4",
      name: "Sarah Pizza",
      email: "sarah@pizza.com",
    },
  },
  {
    id: "3",
    name: "Sushi World",
    image: "/placeholder.svg?height=300&width=500",
    cuisine: "Sushi",
    rating: 4.8,
    deliveryTime: "40-55",
    minimumOrder: 25,
    address: "789 Sushi Blvd, Food City, FC 12345",
    status: "blocked",
    owner: {
      id: "user5",
      name: "Mike Sushi",
      email: "mike@sushi.com",
    },
  },
  {
    id: "4",
    name: "Taco Fiesta",
    image: "/placeholder.svg?height=300&width=500",
    cuisine: "Mexican",
    rating: 4.3,
    deliveryTime: "20-30",
    minimumOrder: 12,
    address: "101 Taco Lane, Food City, FC 12345",
  },
  {
    id: "5",
    name: "Pasta Paradise",
    image: "/placeholder.svg?height=300&width=500",
    cuisine: "Italian",
    rating: 4.6,
    deliveryTime: "35-50",
    minimumOrder: 18,
    address: "202 Pasta Road, Food City, FC 12345",
  },
  {
    id: "6",
    name: "Curry House",
    image: "/placeholder.svg?height=300&width=500",
    cuisine: "Indian",
    rating: 4.4,
    deliveryTime: "30-45",
    minimumOrder: 20,
    address: "303 Curry Circle, Food City, FC 12345",
  },
]

// Pending Restaurant Applications
export const pendingRestaurants = [
  {
    id: "pending1",
    name: "Thai Delight",
    cuisine: "Thai",
    address: "404 Thai Street, Food City, FC 12345",
    owner: {
      id: "user6",
      name: "Lisa Thai",
      email: "lisa@thai.com",
    },
    status: "pending",
    submittedAt: "2023-04-10T10:30:00Z",
  },
  {
    id: "pending2",
    name: "BBQ Masters",
    cuisine: "Barbecue",
    address: "505 Smoke Road, Food City, FC 12345",
    owner: {
      id: "user7",
      name: "Bob BBQ",
      email: "bob@bbq.com",
    },
    status: "pending",
    submittedAt: "2023-04-11T14:45:00Z",
  },
  {
    id: "pending3",
    name: "Vegan Paradise",
    cuisine: "Vegan",
    address: "606 Green Avenue, Food City, FC 12345",
    owner: {
      id: "user8",
      name: "Vicky Vegan",
      email: "vicky@vegan.com",
    },
    status: "rejected",
    submittedAt: "2023-04-09T09:15:00Z",
  },
  {
    id: "pending4",
    name: "Seafood Harbor",
    cuisine: "Seafood",
    address: "707 Ocean Drive, Food City, FC 12345",
    owner: {
      id: "user9",
      name: "Sam Seafood",
      email: "sam@seafood.com",
    },
    status: "approved",
    submittedAt: "2023-04-08T16:20:00Z",
  },
]

// Users
export const users = [
  {
    id: "user1",
    name: "Alice Customer",
    email: "alice@example.com",
    role: "customer",
    status: "active",
    createdAt: "2023-03-15T10:00:00Z",
  },
  {
    id: "user2",
    name: "Bob Delivery",
    email: "bob@example.com",
    role: "delivery",
    status: "active",
    createdAt: "2023-03-16T11:30:00Z",
  },
  {
    id: "user3",
    name: "John Restaurant",
    email: "john@restaurant.com",
    role: "restaurant",
    status: "active",
    createdAt: "2023-03-10T09:15:00Z",
  },
  {
    id: "user4",
    name: "Sarah Pizza",
    email: "sarah@pizza.com",
    role: "restaurant",
    status: "active",
    createdAt: "2023-03-12T14:45:00Z",
  },
  {
    id: "user5",
    name: "Mike Sushi",
    email: "mike@sushi.com",
    role: "restaurant",
    status: "blocked",
    createdAt: "2023-03-05T16:20:00Z",
  },
  {
    id: "user10",
    name: "Admin User",
    email: "admin@system.com",
    role: "admin",
    status: "active",
    createdAt: "2023-02-01T08:00:00Z",
  },
  {
    id: "user11",
    name: "Inactive User",
    email: "inactive@example.com",
    role: "customer",
    status: "inactive",
    createdAt: "2023-03-20T13:10:00Z",
  },
]

// Menu Items
export const menuItems = [
  {
    id: "101",
    restaurantId: "1",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    price: 8.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Burgers",
  },
  {
    id: "102",
    restaurantId: "1",
    name: "Cheese Burger",
    description: "Classic burger with American cheese",
    price: 9.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Burgers",
  },
  {
    id: "103",
    restaurantId: "1",
    name: "Bacon Burger",
    description: "Classic burger with crispy bacon strips",
    price: 10.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Burgers",
  },
  {
    id: "104",
    restaurantId: "1",
    name: "French Fries",
    description: "Crispy golden fries with sea salt",
    price: 3.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Sides",
  },
  {
    id: "105",
    restaurantId: "1",
    name: "Onion Rings",
    description: "Crispy battered onion rings",
    price: 4.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Sides",
  },
  {
    id: "106",
    restaurantId: "1",
    name: "Chocolate Milkshake",
    description: "Creamy chocolate milkshake with whipped cream",
    price: 5.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Drinks",
  },
  {
    id: "201",
    restaurantId: "2",
    name: "Margherita Pizza",
    description: "Classic pizza with tomato sauce, mozzarella, and basil",
    price: 12.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Pizza",
  },
  {
    id: "202",
    restaurantId: "2",
    name: "Pepperoni Pizza",
    description: "Pizza with tomato sauce, mozzarella, and pepperoni",
    price: 14.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Pizza",
  },
]

// Cart Items
export const cartItems = [
  {
    id: "cart1",
    menuItemId: "101",
    name: "Classic Burger",
    price: 8.99,
    quantity: 2,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "cart2",
    menuItemId: "104",
    name: "French Fries",
    price: 3.99,
    quantity: 1,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "cart3",
    menuItemId: "106",
    name: "Chocolate Milkshake",
    price: 5.99,
    quantity: 1,
    image: "/placeholder.svg?height=200&width=200",
  },
]

// Orders
export const orders = [
  {
    id: "d-1745427978456",
    restaurantId: "1",
    restaurantName: "Burger Palace",
    items: [
      {
        id: "item1",
        name: "Classic Burger",
        price: 8.99,
        quantity: 2,
      },
      {
        id: "item2",
        name: "French Fries",
        price: 3.99,
        quantity: 1,
      },
      {
        id: "item3",
        name: "Chocolate Milkshake",
        price: 5.99,
        quantity: 1,
      },
    ],
    status: "delivering",
    total: 27.96,
    createdAt: "2023-04-12T15:30:00Z",
    deliveryAddress: "456 Customer St, Food City, FC 12345",
    deliveryPersonId: "1",
  },
  {
    id: "order2",
    restaurantId: "1",
    restaurantName: "Burger Palace",
    items: [
      {
        id: "item4",
        name: "Cheese Burger",
        price: 9.99,
        quantity: 1,
      },
      {
        id: "item5",
        name: "Onion Rings",
        price: 4.99,
        quantity: 1,
      },
    ],
    status: "preparing",
    total: 14.98,
    createdAt: "2023-04-12T16:15:00Z",
    deliveryAddress: "789 Customer Ave, Food City, FC 12345",
    deliveryPersonId: "1",
  },
  {
    id: "order3",
    restaurantId: "2",
    restaurantName: "Pizza Heaven",
    items: [
      {
        id: "item6",
        name: "Margherita Pizza",
        price: 12.99,
        quantity: 1,
      },
      {
        id: "item7",
        name: "Pepperoni Pizza",
        price: 14.99,
        quantity: 1,
      },
    ],
    status: "pending",
    total: 27.98,
    createdAt: "2023-04-12T16:45:00Z",
    deliveryAddress: "101 Customer Blvd, Food City, FC 12345",
  },
  {
    id: "order4",
    restaurantId: "1",
    restaurantName: "Burger Palace",
    items: [
      {
        id: "item8",
        name: "Bacon Burger",
        price: 10.99,
        quantity: 2,
      },
      {
        id: "item9",
        name: "French Fries",
        price: 3.99,
        quantity: 2,
      },
    ],
    status: "completed",
    total: 29.96,
    createdAt: "2023-04-12T14:00:00Z",
    deliveryAddress: "202 Customer Lane, Food City, FC 12345",
  },
]
